bump: use new node-bindgen
infinyon/fluvio-client-node pull request #371
Opened 2023-08-31 23:09 UTC by ozgrakkurt

closes https://github.com/infinyon/fluvio-client-node/issues/288

Moved node-bindgen dep to master branch. Currently trying to release new node-bindgen to crates.io but have temporary problems so this should be ok for development for now.

Added node 18.17.1 to CI so we can see if new node-bindgen fixes the segfault

2023-09-03 15:07 UTC, ozgrakkurt commented
bors r+

2023-09-03 16:39 UTC, EstebanBorai approved these changes

2023-09-03 16:40 UTC, EstebanBorai commented on .github/workflows/ci.yml
> +        node: ["16", "18"]
I think the changes on node-bindgen will be of help to support NodeJS 20!

2023-09-03 16:42 UTC, EstebanBorai reviewed
Having NodeJS 20 in version test would be helpful as @digikata.

I would also suggest using Latestt along with the last 2 LTS versions.

2023-09-04 11:51 UTC, ozgrakkurt commented
> Having NodeJS 20 in version test would be helpful as @digikata.
> 
> I would also suggest using Latestt along with the last 2 LTS versions.

Seems like there is a mistake in unsafe code inside node-bindgen, I'm going through it to find the error.

First will refactor this https://github.com/infinyon/node-bindgen/blob/master/nj-core/src/lib.rs#L63 so it doesn't hide unsafe code. 

There are functions that pass a raw pointer which is later dereferenced in a lot of places like this: https://github.com/infinyon/node-bindgen/blob/952a08a07b4438a1f1a71b4d0c4937c7d9b61dd2/nj-core/src/basic.rs#L193C5-L193C47

cc: @sehz @digikata

2023-09-04 18:28 UTC, sehz requested changes

2023-09-04 18:28 UTC, sehz commented on Cargo.toml
> +node-bindgen = { git = "https://github.com/infinyon/node-bindgen", branch = "unsafe-rework" }
We should only rely on published or master branches (for development work).  Otherwise mark as draft and use only for testing in PR

2023-09-21 23:06 UTC, morenol commented on .github/workflows/ci.yml
> +        node: ["16", "18"]
```suggestion
        node: ["16", "18.13"]
```

2023-09-26 03:06 UTC, closed without merging